spring:
  cloud:
    gateway:
      routes:
        - id: route1
          uri : lb://client-service
          predicates:
            - Path= /api/client-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: route1CircuitBreaker
                fallbackUri: forward:/clientFallBack

        - id: route2
          uri: lb://produit-service
          predicates:
            - Path= /api/produit-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: route2CircuitBreaker
                fallbackUri: forward:/produitFallBack

        - id: route3
          uri: lb://facturation-service
          predicates:
            - Path= /api/facturation-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: route3CircuitBreaker
                fallbackUri: forward:/facturationFallBack

        - id: route4
          uri: lb://provider-service
          predicates:
            - Path= /api/provider-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: route4CircuitBreaker
                fallbackUri: forward:/providerFallBack

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 50

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 1s
      cancelRunningFuture: true

