apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: elkhaddi/ms:gateway-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: EUREKA_ADRESS
              value: http://eureka-service-discovery.default.svc.cluster.local:8761/eureka

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: api-gateway-service
